### ISSUE TITLE
When building kem with ontology strategy, this error occurs

### ISSUE THREAD

**Issue by david30907d** [UDICatNCHU/kcem#8]
========================== [Experimental Feature] Use kcem to replace keywords into hypernym before training ==========================
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/kem/management/commands/buildkem.py", line 111, in convert2KCEM
    hypernym = kcem.get(word)['value']
  File "/usr/local/lib/python3.5/dist-packages/kcem/apps.py", line 273, in get
    value = self.calculateProbability(self.kcmObject, ngram_keyword, category_set)
  File "/usr/local/lib/python3.5/dist-packages/kcem/apps.py", line 104, in calculateProbability
    return minMaxNormalization({category:toxinomic_score(keyword, category) for category in category_set})
  File "/usr/local/lib/python3.5/dist-packages/kcem/apps.py", line 87, in minMaxNormalization
    M, m = max(candidate.items(), key=lambda x:x[1])[1], min(candidate.items(), key=lambda x:x[1])[1]
ValueError: max() arg is an empty sequence

**Comment by david30907d** [comment]
現在發現 `滬漢蓉高速鐵路`  在db查出來是只有繁簡重定向的parent
但是244卻可以查到完整的 怪了

**Comment by david30907d** [comment]
執行 `python manage.py shell` 後輸入下列程式碼就可以測試問題解決了沒

```python
# -*- coding: utf-8 -*-
from django.apps import AppConfig
from django.db.models import Q
from kcm import KCM
from udic_nlp_API.settings_database import uri
from udicOpenData.dictionary import *
from kcem.models import *
from django.db import connection, connections
from collections import namedtuple
from opencc import OpenCC
from functools import reduce
from collections import defaultdict
from kcem.utils.fullwidth2halfwidth import f2h
import gensim, json, logging, math, pickle, os, psutil, subprocess, time, pymysql
import multiprocessing as mp
from ngram import NGram
from django.db.utils import ProgrammingError, OperationalError

def categorylinks_query(cursor, page_id):
	cursor.execute("SELECT * FROM categorylinks where cl_from = %s", [page_id])
	desc = [col[0] for col in cursor.description]
	result = cursor.fetchall()
	nt_result = namedtuple('Result', desc)
	return (nt_result(*row) for row in result)

openCC = OpenCC('s2t')

databases = connections.databases
cursor = pymysql.connect(connections.databases['default']['HOST'], connections.databases['default']['USER'], connections.databases['default']['PASSWORD'], connections.databases['default']['NAME']).cursor()
category_set = set()
for category in categorylinks_query(cursor, 566178):
	category = openCC.convert(category.cl_to.decode('utf-8'))
	category_set.add(category)


v = Hypernym.objects.get(key='滬漢蓉高速鐵路')
```

**Comment by david30907d** [comment]
重建一次就沒問題...
應該是multiprocess造成每次結果會不一樣
也許是某次記憶體佔滿之後 multiprocess與mysql連線中斷後該次資料遺失然後沒有報錯？

上一次查Hypernym只有繁簡重定向那條而已
也有可能是ＭySQL insert的時候遺失資料

```
>>> v = Hypernym.objects.filter(key='滬漢蓉高速鐵路')
>>> v
<QuerySet [<Hypernym: 滬漢蓉高速鐵路>, <Hypernym: 滬漢蓉高速鐵路>]>
>>> v[1].__dict__
{'_state': <django.db.models.base.ModelState object at 0x7fe985b0b2b0>, 'id': 2093355, 'value': '{"\\u7c21\\u7e41\\u91cd\\u5b9a\\u5411": 0.0}', 'key': '滬漢蓉高速鐵路'}
>>> v[1].__dict__['value']
'{"\\u7c21\\u7e41\\u91cd\\u5b9a\\u5411": 0.0}'
>>> json.loads(v[1].__dict__['value'])
{'簡繁重定向': 0.0}
>>> json.loads(v[0].__dict__['value'])
{'湖北省未來建設': 0.0, '拒絕當選首頁新條目推薦欄目的條目': 0.0, '有未列明來源語句的條目': 0.0, '安徽省未來建設': 0.13518817191055185, '重慶市未來建設': 0.0, '自2017年1月引用不當的條目': 0.0, '四川省未來建設': 0.0, '江蘇省未來建設': 0.13517451801268973, '自2015年4月擴充中的條目': 0.0, '中國高速鐵路線': 0.7296373100767584, '自2018年6月需要合併的條目': 0.0, '未來公共運輸建設': 0.0}
```
